#cloud-config

package_update: true

package_upgrade: true

packages:
    - bc
    - gdal-bin
    - git
    - jq
    - [osmcoastline, '2.3.1-1~bpo11+1']
    - osmium-tool
    - postgis
    - postgresql-13
    - postgresql-13-postgis-3
    - postgresql-13-postgis-3-scripts
    - python3-gdal
    - python3-pyosmium
    - rsync
    - spatialite-bin
    - sqlite3
    - unzip
    - zip

runcmd:
    - [ systemctl, stop, postgresql ]
    - [ systemctl, disable, postgresql ]
    - [ ldconfig ]

