#cloud-config

package_update: true

package_upgrade: true

packages:
    - bc
    - gdal-bin
    - git
    - jq
    - osmcoastline
    - osmium-tool
    - python3-pyosmium
    - rsync
    - spatialite-bin
    - sqlite3
    - unzip
    - zip

