#cloud-config

package_update: true

package_upgrade: true

packages:
    - bc
    - gdal-bin
    - git
    - jq
    - osmcoastline
    - osmium-tool
    - postgis
    - postgresql-15
    - postgresql-15-postgis-3
    - postgresql-15-postgis-3-scripts
    - python3-gdal
    - python3-pyosmium
    - rsync
    - spatialite-bin
    - sqlite3
    - unzip
    - zip

runcmd:
    - [ systemctl, stop, postgresql ]
    - [ systemctl, disable, postgresql ]
    - [ ldconfig ]
    - [ sed, -i, -e, '/deb .*backports/s/# //', '/etc/apt/sources.list' ]
    - [ apt-get, update, --quiet, --yes ]

