#cloud-config

package_update: true

package_upgrade: true

packages:
    - bc
    - gdal-bin
    - git
    - jq
    - osmcoastline
    - osmium-tool
    - postgis
    - postgresql-11
    - postgresql-11-postgis-2.5
    - postgresql-11-postgis-2.5-scripts
    - python-gdal
    - python3-pyosmium
    - rsync
    - spatialite-bin
    - sqlite3
    - unzip
    - zip

runcmd:
    - [ systemctl, stop, postgresql ]
    - [ systemctl, disable, postgresql ]
    - [ ldconfig ]

