#!/bin/sh

# /etc/cron.daily/acmetool

echo "Status:"
acmetool status >/var/log/acmetool/cron.log 2>&1

echo "Updating..."
acmetool reconcile --batch --xlog.severity=debug >>/var/log/acmetool/cron.log 2>&1

